[package]
name = "ann-search-py"
version = "0.2.1"
edition = "2021"
authors = ["Gregor Lueg <gregorlueg@me.com>"]
license = "MIT"
description = "Python bindings for ann-search-rs"
publish = false

[workspace]

[lib]
name = "_ann_search"
crate-type = ["cdylib"]

[features]
default = ["gpu"]
gpu = ["ann-search-rs/gpu", "dep:cubecl"]

[dependencies]
ann-search-rs = { path = "..", default-features = false, features = ["quantised", "serialise", "synthetic"] }
cubecl = { version = "0.10.0", features = ["wgpu"], optional = true }
num-traits = "0.2"
faer = "0.23.2"
numpy = "0.29"
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py310"] }
rayon = "1.11"
tempfile = "3.24"


[profile.release]
lto = "thin"
codegen-units = 1
panic = "unwind"

[profile.dev]
opt-level = 2
