"""Type stubs for the compiled core.

Every handle exposes the same shape, so the surface is described once on
`_Handle` and the eight concrete classes just alias it with their own `build`.
`build` differs per algorithm and is left untyped here rather than repeated
eight times; the estimator classes in `indices.py` are the typed surface.
"""

from pathlib import Path
from typing import Any

import numpy as np

__version__: str

class AnnSearchError(Exception):
    """Base class for every error raised by the Rust core."""

class IndexIoError(AnnSearchError):
    """An index bundle is missing, truncated, or of the wrong kind or dtype."""

def set_num_threads(n: int, /) -> None: ...
def num_threads() -> int: ...
def make_clustered(
    n_samples: int, dim: int, n_clusters: int, seed: int, /
) -> tuple[np.ndarray, np.ndarray]: ...
def make_correlated(
    n_samples: int, dim: int, n_clusters: int, seed: int, cor_strength: float | None, /
) -> tuple[np.ndarray, np.ndarray]: ...
def make_low_rank(
    n_samples: int, dim: int, n_clusters: int, intrinsic_dim: int, seed: int, /
) -> tuple[np.ndarray, np.ndarray]: ...
def make_cell_embeddings(
    n_samples: int, dim: int, n_clusters: int, seed: int, /
) -> tuple[np.ndarray, np.ndarray]: ...
def subsample_queries(x: np.ndarray, n_samples: int, seed: int, /) -> np.ndarray: ...

class _Handle:
    @property
    def dtype(self) -> str: ...
    @property
    def n_samples(self) -> int: ...
    @property
    def dim(self) -> int: ...
    @staticmethod
    def build(x: np.ndarray, **kwargs: Any) -> Any: ...
    def query(
        self,
        q: np.ndarray,
        k: int,
        *,
        return_distance: bool = ...,
        verbose: bool = ...,
        **kwargs: Any,
    ) -> tuple[np.ndarray, np.ndarray | None]: ...
    def query_self(
        self,
        k: int,
        *,
        return_distance: bool = ...,
        verbose: bool = ...,
        **kwargs: Any,
    ) -> tuple[np.ndarray, np.ndarray | None]: ...
    def save(self, path: Path, /) -> None: ...
    @staticmethod
    def load(path: Path, /) -> Any: ...
    def __getstate__(self) -> bytes: ...
    @staticmethod
    def from_bytes(state: bytes, /) -> Any: ...

class Annoy(_Handle): ...
class Exhaustive(_Handle): ...
class Hnsw(_Handle): ...
class Ivf(_Handle): ...
class Kmknn(_Handle): ...
class NnDescent(_Handle): ...
class Nsg(_Handle): ...
class Vamana(_Handle): ...
